@startuml packages_pig
set namespaceSeparator none
package "pig" as pig {
}
package "pig.ai" as pig.ai {
}
package "pig.cheat" as pig.cheat {
}
package "pig.dice" as pig.dice {
}
package "pig.game" as pig.game {
}
package "pig.player" as pig.player {
}
package "pig.scoreboard" as pig.scoreboard {
}
package "pig.shell" as pig.shell {
}
package "pig.turn" as pig.turn {
}
pig.ai --> pig.game
pig.cheat --> pig.game
pig.game --> pig.dice
pig.game --> pig.player
pig.game --> pig.turn
pig.scoreboard --> pig.game
pig.scoreboard --> pig.player
pig.shell --> pig.ai
pig.shell --> pig.cheat
pig.shell --> pig.game
pig.shell --> pig.scoreboard
pig.turn --> pig.dice
pig.turn --> pig.player
@enduml
